
on-creeper-death: # This is for the OnCreeperDeath class
  creeper-explode-on-death: true #If both are on this one takes priority
  creeper-spawn-tnt-on-death: false

team_spawns: # This is where teams spawns are saved
  blue:   #Simply going to save a location object
  red: