name: Oreosplugin
version: '${project.version}'
main: org.oreo.oreo.OreosPlugin
api-version: '1.20'

commands:

  suicide: #simple suicide command
    description: Killing myself rn -nyxiia23 2024
    usage: /<command>
    aliases: [suicide, kms]

  open_gui: #Open the custom gui
    description: Hell yeah -oreo 2024
    usage: /<command>
    aliases: [ kit_gui, kits ]

  team_gui: #Open the custom team gui
    description: Pick a team
    usage: /<command>
    aliases: [ teams ]

  toggle_building: #Toggle building mode
    description: Toggle war mode
    usage: /<command>
    aliases: [ war_toggle , war]